sudo: false
language: csharp 
dist: trusty
dotnet: 2.0.0
services:
  - redis-server 
script: 
  - dotnet restore
  - dotnet build
  - dotnet test Tests
branches:
  only: 
    - master
    - static_constraints

