sudo: false
language: csharp
mono: none
dist: jammy
dotnet: 7.0
services:
  - redis
script:
  - dotnet restore
  - dotnet build
  - dotnet test Tests
branches:
  only:
    - master
    - hopac
    - giraffe
