image: Visual Studio 2022
version: 1.0.{build}
configuration: Release
before_build:
  - nuget install redis-64 -excludeversion -source http://www.nuget.org/api/v2/
  - Redis-64\tools\redis-server.exe --service-install
  - Redis-64\tools\redis-server.exe --service-start
  - dotnet restore
build_script:
  - dotnet build Auctions
test_script:
  - dotnet test Tests
nuget:
  account_feed: false
  project_feed: false
  disable_publish_on_pr: true
branches:
  only:
  - master
  - hopac
  - giraffe